server:
  tomcat:
    max-threads: 20
    min-spare-threads: 5  
logging:
  level:
    com:
      rt:
        mapper: debug

server:
  port: 9010
platformConfig:
  sysName: 转发服务

spring:
  application:
    name: cloudFilm-transpond
  cloud:
    inetutils:
      timeout-seconds: 5
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        instanceHost: 121.204.170.174
        instancePort: ${server.port}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.204.173.49:8635/transpond?useUnicode=true&characterEncoding=utf8
    username: root
    password: Cloud@123
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #阿里数据库连接监控登录名
    loginUsername: admin
    #阿里数据库连接监控登录密码
    loginPassword: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.rt.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

management:
  security:
    enabled: false
    
#统一错误地址
errorUrl: http://192.168.0.118/epatient/#/error

#服务监控，心跳服务配置
monitor:
  #是否开启用服务监控,true开启,false为关闭
  isOpenlogClient: true
  #配置医院ID和医院名称(服务监控)
  hospitalId: 2018120616330919340
  hospitalName: 易联康健康医院
  #配置服务监控的手机联系人及邮箱
  phoneNo: 13708765297
  mailAddress: 345345@qq.com
  #服务名称
  serviceName: cloudFilm-transpond

